[workspace]
channels = ["knime", "conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "*"
knime-extension = "5.8.*"
knime-python-base = "5.8.*"
knime-python-versions = "5.8.*"
intervaltree = "*"
pydotplus = "*"
pip = "*"

[feature.build.dependencies]
python = "*"
knime-extension-bundling = "5.8.*"

[feature.debug.dependencies]
debugpy = "*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "rm -f pixi.lock && python ./.pixi/envs/build/bin/build_python_extension.py . {{ dest }}"}

[environments]
build = {features = ["build"], no-default-feature = true}
debug = {features = ["debug"]}

[pypi-dependencies]
powl = "*"
pm4py = "*"
