<ivy-module version="2.0">
    <info organisation="prom" module="antivy-practice" revision="latest">
    	<description>
    		Version VERSION
    	</description>
    </info>

    <dependencies>
		
		<!-- new versions of dependencies to override what ProM requires -->
		<dependency org="com.thoughtworks.xstream" name="xstream" rev="1.4.21" force="true"/>
		<dependency org="org.xerial" name="sqlite-jdbc" rev="3.51.0.0" force="true"/>
		<dependency org="org.python" name="jython-standalone" rev="2.7.4" force="true"/>
		
	    <dependency org="com.fasterxml.jackson.core" name="jackson-databind"    rev="2.19.2"/>
	    <dependency org="com.fasterxml.jackson.core" name="jackson-core"       rev="2.19.2"/>
	    <dependency org="com.fasterxml.jackson.core" name="jackson-annotations" rev="2.19.2"/>
		
    	<!-- ProM dependencies. -->
    	<!-- Please put every ProM dependency on a single line. -->
    	<!-- ProM framework. -->
    	<!-- category : diccovery -->
    	<dependency org="prom" name="AlphaMiner" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="HeuristicsMiner" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="InductiveMiner" rev="latest" changing="true" transitive="true" />    
    	<dependency org="prom" name="DirectlyFollowsModelMiner" rev="latest" changing="true" transitive="true" />   
    	<dependency org="prom" name="HybridILPMiner" rev="latest" changing="true" transitive="true" />  
    	<dependency org="prom" name="ExtendedHybridMiner" rev="latest" changing="true" transitive="true" /> 
    	<dependency org="prom" name="BPMN" rev="latest" changing="true" transitive="true" />  
    	<dependency org="prom" name="BPMNConversions" rev="latest" changing="true" transitive="true" />      
    	 
    	
    	<!-- https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api -->
		<dependency org="javax.xml.bind" name="jaxb-api" rev="2.4.0-b180830.0359"/>
				
    	
    	<!-- category: manipulation -->
    	<dependency org="prom" name="LogEnhancement" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="LogProjection" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="IncorporateNegativeInformation" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="XESStandard" rev="latest" changing="true" transitive="true"/>
    	<dependency org="prom" name="XESStandardConnector" rev="latest" changing="true" transitive="true"/>
    	
    	
    	<!-- category: conformance and performance -->
    	<dependency org="prom" name="PNetAlignmentAnalysis" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="Performance" rev="latest" changing="true" transitive="true" />	
    	<dependency org="prom" name="ETConformance" rev="latest" changing="true" transitive="true" />	


    </dependencies>
</ivy-module>
