<ivy-module version="2.0">
    <info organisation="prom" module="antivy-practice" revision="latest">
    	<description>
    		Version VERSION
    	</description>
    </info>

    <dependencies>

		<!-- new versions of dependencies to override what ProM requires -->
		<dependency org="com.thoughtworks.xstream" name="xstream" rev="1.4.21" force="true"/>
		<dependency org="org.xerial" name="sqlite-jdbc" rev="3.51.0.0" force="true"/>
		<dependency org="org.python" name="jython-standalone" rev="2.7.4" force="true"/>
		
	    <dependency org="com.fasterxml.jackson.core" name="jackson-databind"    rev="2.19.2"/>
	    <dependency org="com.fasterxml.jackson.core" name="jackson-core"       rev="2.19.2"/>
	    <dependency org="com.fasterxml.jackson.core" name="jackson-annotations" rev="2.19.2"/>
	    
	    <dependency org="com.google.protobuf" name="protobuf-java" rev="3.25.5" force="true"/>
	    <dependency org="org.codehaus.jettison" name="jettison" rev="1.5.4" force="true"/>
	    <dependency org="org.jdom" name="jdom2" rev="2.0.6.1" force="true"/>
	    <dependency org="com.google.guava" name="guava" rev="16.0.1" force="true"/>
		<dependency org="org.beanshell" name="bsh" rev="2.0b4" force="true"/>
	    
	    <!-- https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api -->
		<dependency org="javax.xml.bind" name="jaxb-api" rev="2.4.0-b180830.0359" force="true">
		</dependency>
	    

		
    	<!-- ProM dependencies. -->
    	<!-- Please put every ProM dependency on a single line. -->
    	<!-- ProM framework. -->
    	<!-- category : diccovery -->
    	<dependency org="prom" name="AlphaMiner" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="HeuristicsMiner" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="InductiveMiner" rev="latest" changing="true" transitive="true" />    
    	<dependency org="prom" name="DirectlyFollowsModelMiner" rev="latest" changing="true" transitive="true" />   
    	<dependency org="prom" name="HybridILPMiner" rev="latest" changing="true" transitive="true" />  
    	<dependency org="prom" name="ExtendedHybridMiner" rev="latest" changing="true" transitive="true" /> 
    	<dependency org="prom" name="BPMN" rev="latest" changing="true" transitive="true" />  
    	<dependency org="prom" name="BPMNConversions" rev="latest" changing="true" transitive="true" />      
    	 
    	
    	
    	<!-- category: manipulation -->
    	<dependency org="prom" name="LogEnhancement" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="LogProjection" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="IncorporateNegativeInformation" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="XESStandard" rev="latest" changing="true" transitive="true"/>
    	<dependency org="prom" name="XESStandardConnector" rev="latest" changing="true" transitive="true"/>
    	
    	
    	<!-- category: conformance and performance -->
    	<dependency org="prom" name="PNetAlignmentAnalysis" rev="latest" changing="true" transitive="true" />
    	<dependency org="prom" name="Performance" rev="latest" changing="true" transitive="true" />	
    	<dependency org="prom" name="ETConformance" rev="latest" changing="true" transitive="true" />
    		
    	
    	<!-- Global exclusions -->
    	<exclude org="prom" module="GraphViz"/>
    	<exclude org="org.jdom" module="jdom"/> 
    	<exclude org="io.gatling.uncommons.maths" module="uncommons-maths"/>
    	<exclude org="org.mozilla" module="rhino"/>
    	<exclude org="prom-libs" module="guava"/>
		<exclude org="prom-libs" module="bsh"/>
		
		<exclude org="prom-libs" module="flanagan"/>
		<exclude org="prom-libs" module="javabdd"/>
		<exclude org="prom-libs" module="ujmp-complete"/>
		<exclude org="prom-libs" module="gurobi"/>
		<exclude org="prom-libs" module="jas-plotter"/>
		<exclude org="prom-libs" module="javailp"/>
		<exclude org="prom-libs" module="japura"/>
		<exclude org="prom-libs" module="jbpt"/>
		<exclude org="prom-libs" module="saxon"/>
		<exclude org="prom-libs" module="simmetrics"/>
		<exclude org="prom-libs" module="jargs"/>
		<exclude org="prom-libs" module="org.eclipse.uml2.uml"/>
		<exclude org="prom-libs" module="javacsv"/>
		<exclude org="prom-libs" module="opencsv"/>
		<exclude org="prom-libs" module="AccessCPN"/>
		<exclude org="prom-libs" module="org.eclipse.emf.ecore"/>
		<exclude org="prom-libs" module="YAWLEditor"/>
		<exclude org="prom-libs" module="jmathplot"/>
		<exclude org="prom-libs" module="FilterableSortableTablePanel"/>
		<exclude org="prom-libs" module="openide-lookup"/>
		<exclude org="prom-libs" module="jgrapht"/>


    </dependencies>
</ivy-module>
